name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza 2x por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: "analessp"
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Deploy no branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
